import sequelize from "../config/db";
import { DataTypes, Model } from "sequelize";
import { v4 as UUIDV4 } from "uuid";
import Course from "./course";
import User from "./user";

class courseCertificate extends Model{
    public uuid!: string;
    public studentId!: string;
    public courseId!: string;
    public isAutoGenerated!: boolean;
};


courseCertificate.init({
    uuid:{
        type: DataTypes.UUID,
        defaultValue: UUIDV4,
        primaryKey: true,
        allowNull: false
    },
    isAutoGenerated:{
        type: DataTypes.BOOLEAN,
        defaultValue: true
    }
},{
    sequelize,
    modelName: "course_certificate",
    paranoid: true,
    timestamps: true
});

Course.hasMany(courseCertificate, { foreignKey:"courseId", onDelete: "CASCADE", onUpdate:"CASCADE", as:"certificateCourse"});
courseCertificate.belongsTo(Course, { foreignKey:"courseId", onDelete: "CASCADE", onUpdate:"CASCADE", as:"certificateCourse"});

User.hasMany(courseCertificate, { foreignKey:"studentId", onDelete: "CASCADE", onUpdate:"CASCADE", as:"certificateUser"});
courseCertificate.belongsTo(User, { foreignKey:"studentId", onDelete: "CASCADE", onUpdate:"CASCADE", as:"certificateUser"});