import sequelize from "../config/db";
import { DataTypes, Model } from "sequelize";
import { v4 as UUIDV4 } from "uuid";
import Course from "./course";
import User from "./student";

class studentCertificate extends Model{
    public uuid!: string;
    public studentId!: string;
    public courseId!: string;
    public key!: string;
    public isAutoGenerated!: boolean;
};


studentCertificate.init({
    uuid:{
        type: DataTypes.UUID,
        defaultValue: UUIDV4,
        primaryKey: true,
        allowNull: false
    },
    key:{
        type: DataTypes.STRING,
        allowNull: false
    },
    isAutoGenerated:{
        type: DataTypes.BOOLEAN,
        defaultValue: true
    }
},{
    sequelize,
    modelName: "course_certificate",
    paranoid: true,
    timestamps: true
});

Course.hasMany(studentCertificate, { foreignKey:"courseId", onDelete: "CASCADE", onUpdate:"CASCADE", as:"certificateCourse"});
studentCertificate.belongsTo(Course, { foreignKey:"courseId", onDelete: "CASCADE", onUpdate:"CASCADE", as:"certificateCourse"});

User.hasMany(studentCertificate, { foreignKey:"studentId", onDelete: "CASCADE", onUpdate:"CASCADE", as:"certificateUser"});
studentCertificate.belongsTo(User, { foreignKey:"studentId", onDelete: "CASCADE", onUpdate:"CASCADE", as:"certificateUser"});

export default studentCertificate;